# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        env:
          - PYTORCH_CHANNEL='pytorch' PYTORCH_VERSION='=1.7.1' COVERAGE='--cov geoopt'
          - PYTORCH_CHANNEL='pytorch' PYTORCH_VERSION='=1.6.0' COVERAGE=''
          - PYTORCH_CHANNEL='pytorch' PYTORCH_VERSION='=1.5.1' COVERAGE=''
          - PYTORCH_CHANNEL='pytorch-nightly' PYTORCH_VERSION='' COVERAGE=''

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        channels: conda-forge
        python-version: ${{ matrix.python-version }}
    - name: Install deps with conda
      shell: bash -l {0}
      run: |
        export ${{ matrix.env }}
        conda install --yes numpy mkl-service
        conda install --yes pytorch${PYTORCH_VERSION} cpuonly -c ${PYTORCH_CHANNEL}
        conda install --yes --file requirements-dev.txt
        conda install --yes conda-build
        conda develop .
    - name: Run info
      shell: bash -l {0}
      run: |
        conda --version && which python && python --version && python -c 'import torch; print("torch", torch.__version__)'
    - name: Run Linters
      shell: bash -l {0}
      run: make lint
    - name: Run Tests
      shell: bash -l {0}
      run: |
        export ${{ matrix.env }}
        pytest -v geoopt tests --durations=0 --doctest-modules ${COVERAGE}
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
